#%%
#=============================================================
# Import modules
#=============================================================
import tensorflow as tf
from pickle import load
import numpy as np
from scipy.interpolate import RBFInterpolator
from sklearn.neighbors import NearestNeighbors
from scipy import stats

class AoValveHalf():
    """ For all your collocation needs . 
        
        Arguments
        ----------
        collocationpaths : list
            List of paths to collocation data, generated by freecad.
            [0]:    standard collocation data
            [1]:    dense collocation data
            [2]:    medium collocation data
            [3]:    sparse collocation data

        scaling_l : float
            Characteristic length of the domain. Default is 1.0.

        wallpath : str
            Path to polynomial vertices that trace the boundary wall, generated by freecad. Default is "".
        
        Parameters
        ----------
        condargs : dict
            Dictionary of hyperparamters for the conditioning operations. Default is {"sigma": 10.0, "threshold": 0.9}.
    """ 

    def __init__(self, scaling_l:float=1.0, prec=tf.float32) -> None:

        self.scaling_l        = scaling_l
        self.condargs         = {"sigma": 10.0, "threshold": 0.9, "smoothing":10}
        self.prec = prec

        # Instantiate an instance of the Distances class, used for calculating boundary distances.
        self.distances = Distances(self.prec)

    def init_freecad(self, collocationpaths:list, wallpath:str=""):

        self.collocationpaths = collocationpaths
        self.wallpath         = wallpath

        # Import collocation data

        self.standard_collocation = self.single_import(self.collocationpaths[0], self.scaling_l)[0]
        self.standard_normals     = self.single_import(self.collocationpaths[0], self.scaling_l)[1]

        if len(self.collocationpaths) > 1:
            self.dense_collocation    = self.single_import(self.collocationpaths[1], self.scaling_l)[0]
            self.med_collocation      = self.single_import(self.collocationpaths[2])[0]
            self.sparse_collocation   = self.single_import(self.collocationpaths[3], self.scaling_l)[0]
    
    def init_rect(self, h, w):

        self.h = h
        self.w = w

    def single_import(self, path:str="", scaling_l:float=1.0):
        """ Imports a single collocation dataset, generated by freecad. """

        X_fluid, X_in, X_out, X_wall, X_symmetry, N_wall, N_symmetry = load(open(path, 'rb'))

        X_fluid     = tf.convert_to_tensor(X_fluid/scaling_l, dtype=self.prec)
        X_in        = tf.convert_to_tensor(X_in/scaling_l, dtype=self.prec)
        X_out       = tf.convert_to_tensor(X_out/scaling_l, dtype=self.prec)
        X_wall      = tf.convert_to_tensor(X_wall/scaling_l, dtype=self.prec)
        X_symmetry  = tf.convert_to_tensor(X_symmetry/scaling_l, dtype=self.prec)

        self.N_wall     = tf.convert_to_tensor(N_wall, dtype=self.prec)
        self.N_symmetry = tf.convert_to_tensor(N_symmetry, dtype=self.prec)

        standard_collocation = [X_fluid, X_in, X_out, X_wall, X_symmetry]
        standard_normals     = [N_wall, N_symmetry]
        return standard_collocation, standard_normals
    
    def mesh(self, X, n=10, inverse_distance=True):
        """ Create the connectivity matrix for graph convolutional neural networks .     
        """ 

        adiv = 1000

        A = NearestNeighbors(n_neighbors=n, algorithm="brute").fit(X).kneighbors_graph(X, mode="distance").toarray()

        A_hat = A
        amax = np.max(A)
        if inverse_distance == False:
            for i, x in enumerate(A_hat):
                for j, y in enumerate(x):
                    if y != 0.0:
                        A_hat[i, j] = amax - A_hat[i, j]
        
        D = np.sum(A_hat, axis=0)
        A_hat = A_hat/np.max(A_hat)/adiv
        A_hat = A_hat + np.diag(np.ones(A_hat.shape[0]))

        assert np.sum(A_hat - A_hat.T) < 1E-6, f"Adjacency matrix not symmetric with error{np.sum(A_hat - A_hat.T)}"

        return A, D, tf.sparse.from_dense(tf.convert_to_tensor(A_hat, dtype=self.prec))

    def condition(self, X, T_in, Y_in):
        """ Perform conditioning on a field to improve numerical performance . 
            Operations performed:
                - Remove nans
                - Remove outliers
                - Smooth non smooth data
            
            Arguments
            ----------
            X : tf.Tensor
                Coordinates of collocation points
            
            T_in : list
                List of tensors to check for nans and outliers

            Y_in : list
                List of tensors to apply the same operations to as T_in

            args: dict
                Dictionary of hyperparamters for the conditioning operations.
        """ 

        def id_nans(T, I_err):
            """Appends the boolean mask of entries that have nans in any of the columns of T to I_err"""

            I     = tf.expand_dims(tf.reduce_any(tf.where(tf.math.is_nan(T), tf.zeros_like(T, dtype=tf.bool),
                                                          tf.ones_like(T, dtype=tf.bool)), axis=1), axis=1)
            I_err = tf.concat([I_err,I],axis=1)
            
            return I_err
        
        def id_outliers(T, I_err):
            """Appends the boolean mask of entries that are outliers in any of the columns of T to I_err"""

            for d in range(T.shape[1]):
                # find outliers
                T_mean = tf.math.reduce_mean(T[:,d])
                T_std = tf.math.reduce_std(T[:,d])
                I_outlier = tf.where(tf.math.logical_or(T[:,d] > T_mean + self.condargs["sigma"]*T_std, T[:,d] < T_mean - self.condargs["sigma"]*T_std),
                                    tf.zeros_like(T[:,d], dtype=tf.bool), tf.ones_like(T[:,d], dtype=tf.bool))
                I_outlier = tf.expand_dims(I_outlier, axis=1)
                I_err = tf.concat([I_err,I_outlier],axis=1)

            return I_err
        
        def id_smooth(X, T, I_err):
            """Appends the boolean mask of entries that are outliers in any of the columns of T to I_err"""

            threshold = self.condargs["threshold"]*self.scaling_l

            for d in range(T.shape[1]):
                # find outliers

                rbf = RBFInterpolator(X.numpy(), T[:,d].numpy(), smoothing=self.condargs["smoothing"])(X.numpy())

                I_outlier = tf.where(tf.convert_to_tensor(np.abs(rbf - T[:,d].numpy()), dtype=self.prec) > threshold,
                                      tf.zeros_like(T[:,d], dtype=tf.bool), tf.ones_like(T[:,d], dtype=tf.bool))
                I_outlier = tf.expand_dims(I_outlier, axis=1)
                I_err = tf.concat([I_err,I_outlier],axis=1)

            return I_err
        
        T_out = []
        Y_out = []
        X = X[0]

        # Remove nan entries
        I_err = tf.Variable(tf.ones_like(T_in[0][:,0:1], dtype=tf.bool))
        for T in T_in:
            I_err = id_nans(T, I_err)
        I_err = tf.reduce_all(I_err, axis=1)

        for i, T in enumerate(T_in):
            T_in[i] =  tf.boolean_mask(T, I_err)

        for i, Y in enumerate(Y_in):
            Y_in[i] =  tf.boolean_mask(Y, I_err)

        X = tf.boolean_mask(X, I_err)

        # # Remove statistical outliers
        # I_err = tf.Variable(tf.ones_like(T_in[0][:,0:1], dtype=tf.bool))
        # for T in T_in:
        #     I_err = id_outliers(T, I_err)
        # I_err = tf.reduce_all(I_err, axis=1)

        # for i, T in enumerate(T_in):
        #     T_in[i] =  tf.boolean_mask(T, I_err)

        # for i, Y in enumerate(Y_in):
        #     Y_in[i] =  tf.boolean_mask(Y, I_err)

        # X = tf.boolean_mask(X, I_err)

        # Remove smoothness outliers
        I_err = tf.Variable(tf.ones_like(T_in[0][:,0:1], dtype=tf.bool))
        for T in T_in:
            I_err = id_smooth(X, T, I_err)
        I_err = tf.reduce_all(I_err, axis=1)


        for i, T in enumerate(T_in):
            T_in[i] =  tf.boolean_mask(T, I_err)

        for i, Y in enumerate(Y_in):
            Y_in[i] =  tf.boolean_mask(Y, I_err)

        X = tf.boolean_mask(X, I_err)

        T_out = T_in
        Y_out = Y_in
        X_out = X

        return X_out, T_out, Y_out

    def rect_coll(self, ncol):
        """ Returns a tensor of ncol points in a rectangle of width w and height h. """

        X_fluid         = stats.qmc.Sobol(2, seed = 10).random_base2(ncol[0])
        X_fluid[:,0]    = X_fluid[:,0]*self.w ; X_fluid[:,1] = X_fluid[:,1]*self.h
        X_fluid         = tf.convert_to_tensor(X_fluid, dtype=self.prec)

        X_wall                              = stats.qmc.Sobol(2, seed = 10)
        X_wall                              = X_wall.random_base2(ncol[1])
        X_wall[0:int(X_wall.shape[0]/2), 1] = X_wall[0:int(X_wall.shape[0]/2), 1]*0
        X_wall[int(X_wall.shape[0]/2)::, 1] = np.ones(int(X_wall.shape[0]/2))*self.h
        X_wall[:, 0]                        = X_wall[:, 0]*self.w
        X_wall                              = tf.convert_to_tensor(X_wall, dtype=self.prec)

        X_in = np.hstack((0*np.ones(2**ncol[2])[: , np.newaxis],
                          self.h*stats.qmc.Sobol(1, seed = 10).random_base2(ncol[2])))
        X_in = tf.convert_to_tensor(X_in, dtype=self.prec)

        X_out   = np.hstack((self.w*np.ones(2**ncol[3])[: , np.newaxis],
                             self.h*stats.qmc.Sobol(1, seed = 10).random_base2(ncol[3])))
        X_out   = tf.convert_to_tensor(X_out, dtype=self.prec)

        # Scaling:
        X_fluid = X_fluid/self.scaling_l
        X_wall  = X_wall/self.scaling_l
        X_in    = X_in/self.scaling_l
        X_out   = X_out/self.scaling_l

        return X_fluid, X_in, X_out, X_wall
    
    def freecad_coll(self):
        """Returns collocation points, generated by freecad as a list of tensors."""

        return self.standard_collocation
    
    def freecad_coll_tiered(self):
        """Returns collocation points with separate zones of density."""

        threshold   = 1/self.scaling_l

        X_dense     = self.dense_collocation
        X_med       = self.med_collocation
        X_sparse    = self.sparse_collocation

        X_d         = self.floaters_distances(X_dense, kind="bound")
        X_dense     = tf.boolean_mask(X_dense[0], X_d[:,0] < threshold)
        
        X_d         = self.floaters_distances(X_sparse, kind="bound")
        X_sparse    = tf.boolean_mask(X_sparse[0], X_d[:,0] > threshold)

        X_fluid     = tf.concat([X_dense[:,0:2], X_sparse[:,0:2]], axis=0)

        return X_fluid
    
    def freecad_normal(self):
        """ Returns the normal vectors of the collocation points, generated by freecad as a list of tensors."""

        return self.standard_normals
    
    def floaters_distances(self, Xs, kind="wall"):
        """ Returns the boundary or wall distances of collocation points using floaters mean value coordinates"""

        assert self.wallpath != "", "Wallpath must be set to use floaters distances"

        if kind == "wall":
            X_d = self.distances.floaters_wall(Xs[0][:,0:2], self.wallpath, Xs[2][0,0], Xs[3][0,1], self.scaling_l)
        elif kind == "bound":
            X_d = self.distances.floaters_bound(Xs[0][:,0:2], self.wallpath, Xs[2][0,0], Xs[3][0,1], self.scaling_l)
        else:
            raise ValueError("kind must be either 'wall' or 'bound'")

        return X_d
    
    def floaters_hard(self, Xs, inletfatness, carryalong, do_condition):
        """ Returns the boundary distances and derivatives required for hard constraints. """

        assert self.wallpath != "", "Wallpath must be set to use floaters distances"

        hard_ds = self.distances.floaters_hard(Xs[0][:,0:2], self.wallpath, Xs[2][0,0], Xs[3][0,1],
                                                inletfatness, self.condition, self.scaling_l,carryalong, do_condition)
        X_fluid     = hard_ds[0]
        Fs          = hard_ds[1]
        carryalong = hard_ds[2]

        return X_fluid, Fs, carryalong
    
    def rect_floaters_distances(self, Xs, kind="wall"):
        """ Returns the boundary or wall distances of collocation points using floaters mean value coordinates"""

        if kind == "wall":
            X_d = self.distances.rect_floaters_wall(Xs[0][:,0:2], self.w, self.h, self.scaling_l)
        elif kind == "bound":
            X_d = self.distances.rect_floaters_bound(Xs[0][:,0:2], self.w, self.h, self.scaling_l)
        else:
            raise ValueError("kind must be either 'wall' or 'bound'")

        return X_d
    
    def rect_floaters_hard(self, Xs, inletfatness, carryalong, do_condition):
        """ Returns the boundary distances and derivatives required for hard constraints. """

        hard_ds = self.distances.rect_floaters_hard(Xs[:,0:2], self.w, self.h,
                                                inletfatness, self.condition, self.scaling_l,carryalong, do_condition)
        X_fluid     = hard_ds[0]
        Fs          = hard_ds[1]
        carryalong = hard_ds[2]

        return X_fluid, Fs, carryalong
    
class Distances():
    """ Class to compute wall and boundary distances using various methods . 
        
        Notes
        ----- 
        Current distance calculation methods:
            - floaters mean value coordinates
    
    """ 

    def __init__(self, prec) -> None:
        self.prec = prec
        pass

    def Fl(self, Xvert, X):
            """ Returns the floaters mean value coordinates of locations (X) with respect to polygon vertices (Xvert)."""
            
            Xvert_t = tf.roll(Xvert, 1, axis=0)

            def Fl_inner(X_inputs):
                xvert   = X_inputs[0]
                xvert_t = X_inputs[1]
                x       = X_inputs[2]

                ri   = xvert - x
                rii  = xvert_t - x
                nri  = tf.norm(ri)
                nrii = tf.norm(rii)
                ti   = (ri[0]*rii[1] - ri[1]*rii[0])/(nri*nrii + tf.tensordot(ri, rii, axes=1))

                w    = (1/nri + 1/nrii)*ti

                return w

            def Fl_outer(X_inputs):

                X_vert   = X_inputs[0]
                X_vert_t = X_inputs[1]
                x        = tf.tile(tf.expand_dims(X_inputs[2], axis=0), (X_vert.shape[0],1))

                W        = tf.reduce_sum(tf.vectorized_map(Fl_inner, [X_vert, X_vert_t, x]))

                return W
            
            phi = tf.vectorized_map(Fl_outer, [tf.tile(tf.expand_dims(Xvert, axis=0), (X.shape[0],1,1)),
                                               tf.tile(tf.expand_dims(Xvert_t, axis=0), (X.shape[0],1,1)), X])

            return tf.expand_dims(2/phi, axis=1)

    def floaters_wall(self, X_fluid:tf.Tensor, wallpath:str, l_domain:float, d_aorta:float, scaling_l:float):
        """ Return distances from the wall boundary condition using floaters mean value coordinates. """

        # Vertices for Xf_wall
        Xf_wall, _ = load(open(wallpath, 'rb'))
        Xf_wall    = Xf_wall[:,0:2]/scaling_l
        Xf_wall    = np.vstack((np.array([[-10/scaling_l, d_aorta]]), Xf_wall))
        Xf_wall    = np.vstack((Xf_wall, np.array([[l_domain*2, d_aorta]])))
        Xf_wall    = np.vstack((Xf_wall, np.array([[l_domain*2, -10/scaling_l]])))
        Xf_wall    = np.vstack((Xf_wall, np.array([[-10/scaling_l,-10/scaling_l]])))
        Xf_wall    = np.flip(Xf_wall, axis=0)
        Xf_wall    = tf.convert_to_tensor(Xf_wall, dtype=self.prec)

        F_wall     = -self.Fl(Xf_wall,X_fluid)

        return F_wall
    
    
    def floaters_bound(self, X_fluid:tf.Tensor, wallpath:str, l_domain:float, d_aorta:float, scaling_l:float):
        """ Return distances from all boundary conditions using floaters mean value coordinates. """

        # Vertices for Xf_bound
        Xf_bound, _ = load(open(wallpath, 'rb'))
        Xf_bound    = Xf_bound[:,0:2]/scaling_l
        # Xf_bound = np.vstack((Xf_bound, np.array([[l_domain, d_aorta]])))
        Xf_bound    = np.vstack((Xf_bound, np.array([[l_domain, 0]])))
        Xf_bound    = np.vstack((Xf_bound, np.array([[0,0]])))
        Xf_bound    = np.flip(Xf_bound, axis=0)
        Xf_bound    = tf.convert_to_tensor(Xf_bound, dtype=self.prec)

        F_bound     = -self.Fl(Xf_bound,X_fluid)

        return F_bound
    
    def floaters_hard(self, X_fluid:tf.Tensor, wallpath:str, l_domain:float, d_aorta:float,
                            inletfatness:float, conditioner, scaling_l:float, carryalong:list, do_condition:bool):
        """ Returns all the spacial fields required to enforce hard constraints, using floaters mean value  coordinates. """

        def fat_inlet(walldist, inletfatness):

            bounddist1      = X_fluid[:,0:1]
            bounddist2      = -X_fluid[:,0:1] + inletfatness/scaling_l
            zero_function   = tf.zeros_like(walldist)
            power           = 2
            walldist        = tf.math.minimum(bounddist2**power*zero_function + 
                                              bounddist1**power*walldist/(bounddist1**power + bounddist2**power),
                                              walldist)
            return walldist

        # Vertices for Xf_out
        Xf_out = np.array([[-100/scaling_l,-100/scaling_l]])
        Xf_out = np.vstack((Xf_out, np.array([[-100/scaling_l,100/scaling_l]])))
        Xf_out = np.vstack((Xf_out, np.array([[l_domain,100/scaling_l]])))
        Xf_out = np.vstack((Xf_out, np.array([[l_domain, -100/scaling_l]])))
        Xf_out = np.flip(Xf_out, axis=0)
        Xf_out = tf.convert_to_tensor(Xf_out, dtype=self.prec)

        # Vertices for Xf_in
        Xf_in = np.array([[0,-50/scaling_l]])
        Xf_in = np.vstack((Xf_in, np.array([[0,50/scaling_l]])))
        Xf_in = np.vstack((Xf_in, np.array([[200/scaling_l,50/scaling_l]])))
        Xf_in = np.vstack((Xf_in, np.array([[200/scaling_l,-50/scaling_l]])))
        Xf_in = np.flip(Xf_in, axis=0)
        Xf_in = tf.convert_to_tensor(Xf_in, dtype=self.prec)

        # Vertices for Xf_sym
        Xf_sym = np.array([[-10/scaling_l,0]])
        Xf_sym = np.vstack((Xf_sym, np.array([[-10/scaling_l,50]])))
        Xf_sym = np.vstack((Xf_sym, np.array([[100/scaling_l,50]])))
        Xf_sym = np.vstack((Xf_sym, np.array([[100/scaling_l,0]])))
        Xf_sym = np.flip(Xf_sym, axis=0)
        Xf_sym = tf.convert_to_tensor(Xf_sym, dtype=self.prec)

        # Vertices for Xf_wall
        Xf_wall, _ = tf.convert_to_tensor(load(open(wallpath, 'rb')), self.prec)
        Xf_wall = Xf_wall[:,0:2]/scaling_l
        Xf_wall = np.vstack((np.array([[-10/scaling_l, d_aorta]]), Xf_wall))
        Xf_wall = np.vstack((Xf_wall, np.array([[l_domain*2, d_aorta]])))
        Xf_wall = np.vstack((Xf_wall, np.array([[l_domain*2, -10/scaling_l]])))
        Xf_wall = np.vstack((Xf_wall, np.array([[-10/scaling_l,-10/scaling_l]])))
        Xf_wall = np.flip(Xf_wall, axis=0)
        Xf_wall = tf.convert_to_tensor(Xf_wall, dtype=self.prec)

        # # Calculate Fp, Fu, Fv
        with tf.GradientTape(persistent=True) as tape:
            tape.watch(X_fluid)

            F_in    = fat_inlet(-self.Fl(Xf_in,X_fluid), inletfatness)
            F_out   = -self.Fl(Xf_out,X_fluid)
            F_wall  = -self.Fl(Xf_wall,X_fluid)
            F_sym   = -self.Fl(Xf_sym,X_fluid)

            n  = 4

            w_in    =   (F_wall*F_out)/(F_out*F_wall + F_in*F_wall + F_in*F_out)
            w_out   =   (F_in*F_wall)/(F_out*F_wall + F_in*F_wall + F_in*F_out)

            w_wall  =   (F_in*F_out*F_sym**n)/(F_out*F_sym**n*F_wall + F_in*F_sym**n*F_wall + F_in*F_out*F_wall + F_in*F_out*F_sym**n)

            w_sym   =   (F_in*F_out*F_wall)/(F_out*F_sym**n*F_wall + F_in*F_sym**n*F_wall + F_in*F_out*F_wall + F_in*F_out*F_sym**n)

        dF_in   = tape.gradient(F_in, X_fluid)
        dF_out  = tape.gradient(F_out, X_fluid)
        dF_wall = tape.gradient(F_wall, X_fluid)
        dF_sym  = tape.gradient(F_sym, X_fluid)
        dw_in   = tape.gradient(w_in, X_fluid)
        dw_out  = tape.gradient(w_out, X_fluid)
        dw_wall = tape.gradient(w_wall, X_fluid)
        dw_sym  = tape.gradient(w_sym, X_fluid)
        del tape

        if do_condition:
            X_fluid, [F_in, F_out, F_wall, F_sym, dF_in, dF_out, dF_wall, dF_sym,
                    w_in, w_out, w_wall, w_sym, dw_in, dw_out, dw_wall, dw_sym], carryalong = conditioner([X_fluid], 
                                                        [F_in, F_out, F_wall, F_sym, dF_in, dF_out, dF_wall, dF_sym, 
                                                        w_in, w_out, w_wall, w_sym, dw_in, dw_out, dw_wall, dw_sym], carryalong)

        return X_fluid, [F_in, F_out, F_wall, F_sym, dF_in, dF_out, dF_wall, dF_sym, w_in, w_out, w_wall,
                        w_sym, dw_in, dw_out, dw_wall, dw_sym], carryalong
    
    def rect_floaters_wall(self, X_fluid:tf.Tensor, w:float, h:float, scaling_l:float):
        """ Return distances from the wall boundary condition using floaters mean value coordinates. """

        h, w = h/scaling_l, w/scaling_l

        # Vertices for Xf_wall
        Xf_wall = np.array([[-10/scaling_l,0]])
        Xf_wall = np.vstack((Xf_wall, np.array([[-10/scaling_l,h]])))
        Xf_wall = np.vstack((Xf_wall, np.array([[100/scaling_l,h]])))
        Xf_wall = np.vstack((Xf_wall, np.array([[100/scaling_l,0]])))
        Xf_wall = np.flip(Xf_wall, axis=0)
        Xf_wall = tf.convert_to_tensor(Xf_wall, dtype=self.prec)

        F_wall     = -self.Fl(Xf_wall,X_fluid)

        return F_wall
    
    
    def rect_floaters_bound(self, X_fluid:tf.Tensor, w:float, h:float, scaling_l:float):
        """ Return distances from all boundary conditions using floaters mean value coordinates. """

        h, w = h/scaling_l, w/scaling_l

        # Vertices for Xf_bound
        Xf_bound = np.array([[0,0]])
        Xf_bound = np.vstack((Xf_bound, np.array([[0,h]])))
        Xf_bound = np.vstack((Xf_bound, np.array([[w,h]])))
        Xf_bound = np.vstack((Xf_bound, np.array([[w,0]])))
        Xf_bound = np.flip(Xf_bound, axis=0)
        Xf_bound = tf.convert_to_tensor(Xf_bound, dtype=self.prec)

        F_bound     = -self.Fl(Xf_bound,X_fluid)

        return F_bound
    
    def rect_floaters_hard(self, X_fluid:tf.Tensor, w:float, h:float,
                            inletfatness:float, conditioner, scaling_l:float, carryalong:list, do_condition:bool):
        """ Returns all the spacial fields required to enforce hard constraints, using floaters mean value  coordinates. """

        h, w = h/scaling_l, w/scaling_l

        def fat_inlet(walldist, inletfatness):

            bounddist1      = X_fluid[:,0:1]
            bounddist2      = -X_fluid[:,0:1] + inletfatness/scaling_l
            zero_function   = tf.zeros_like(walldist)
            power           = 2
            walldist        = tf.math.minimum(bounddist2**power*zero_function + 
                                              bounddist1**power*walldist/(bounddist1**power + bounddist2**power),
                                              walldist)
            return walldist

        # Vertices for Xf_out
        Xf_out = np.array([[-100/scaling_l,-100/scaling_l]])
        Xf_out = np.vstack((Xf_out, np.array([[-100/scaling_l,100/scaling_l]])))
        Xf_out = np.vstack((Xf_out, np.array([[w,100/scaling_l]])))
        Xf_out = np.vstack((Xf_out, np.array([[w, -100/scaling_l]])))
        Xf_out = np.flip(Xf_out, axis=0)
        Xf_out = tf.convert_to_tensor(Xf_out, dtype=self.prec)

        # Vertices for Xf_in
        Xf_in = np.array([[0,-50/scaling_l]])
        Xf_in = np.vstack((Xf_in, np.array([[0,50/scaling_l]])))
        Xf_in = np.vstack((Xf_in, np.array([[200/scaling_l,50/scaling_l]])))
        Xf_in = np.vstack((Xf_in, np.array([[200/scaling_l,-50/scaling_l]])))
        Xf_in = np.flip(Xf_in, axis=0)
        Xf_in = tf.convert_to_tensor(Xf_in, dtype=self.prec)

        # Vertices for Xf_wall
        Xf_wall = np.array([[-10/scaling_l,0]])
        Xf_wall = np.vstack((Xf_wall, np.array([[-10/scaling_l,h]])))
        Xf_wall = np.vstack((Xf_wall, np.array([[100/scaling_l,h]])))
        Xf_wall = np.vstack((Xf_wall, np.array([[100/scaling_l,0]])))
        Xf_wall = np.flip(Xf_wall, axis=0)
        Xf_wall = tf.convert_to_tensor(Xf_wall, dtype=self.prec)

        # # Calculate Fp, Fu, Fv
        with tf.GradientTape(persistent=True) as tape:
            tape.watch(X_fluid)

            F_in    = fat_inlet(-self.Fl(Xf_in,X_fluid), inletfatness)
            F_out   = -self.Fl(Xf_out,X_fluid)
            F_wall  = -self.Fl(Xf_wall,X_fluid)

            n  = 4

            w_in    =   (F_wall*F_out)/(F_out*F_wall + F_in*F_wall + F_in*F_out)
            w_out   =   (F_in*F_wall)/(F_out*F_wall + F_in*F_wall + F_in*F_out)

            w_wall  =   (F_in*F_out)/(F_out*F_wall + F_in*F_wall + F_in*F_out)

        dF_in   = tape.gradient(F_in, X_fluid)
        dF_out  = tape.gradient(F_out, X_fluid)
        dF_wall = tape.gradient(F_wall, X_fluid)
        dw_in   = tape.gradient(w_in, X_fluid)
        dw_out  = tape.gradient(w_out, X_fluid)
        dw_wall = tape.gradient(w_wall, X_fluid)
        del tape

        if do_condition:
            X_fluid, [F_in, F_out, F_wall, dF_in, dF_out, dF_wall,
                    w_in, w_out, w_wall, dw_in, dw_out, dw_wall], carryalong = conditioner([X_fluid],[F_in, F_out, F_wall, dF_in, dF_out, dF_wall, w_in, w_out, w_wall, dw_in, dw_out, dw_wall], carryalong)

        return X_fluid, [F_in, F_out, F_wall, dF_in, dF_out, dF_wall, w_in, w_out, w_wall, dw_in, dw_out, dw_wall], carryalong

if __name__ == "__main__":
    from matplotlib import pyplot as plt

    angle   = 45
    homedir = "/media/jflinux_main/HDD/Studies/Studies_MEngM/Navorsing/HeartPINN/Phase_3/chpc/data/"
    collocationpaths = [f"{homedir}valve45.013.pkl",
                        f"{homedir}valve45.014.pkl",
                        f"{homedir}valve45.013.pkl",
                        f"{homedir}valve45.012.pkl",]
    wallpath         =  f"{homedir}wall_float45.0.pkl"
    valve = AoValveHalf(scaling_l=10, collocationpaths=collocationpaths, wallpath=wallpath)

    # X_f = valve.freecad_coll()
    # X_f, X_d, _ = valve.floaters_hard(X_f, inletfatness=10, carryalong=[])

    # a = 3
    # plt.figure(figsize=(15*1.5,3*1.5))
    # plt.scatter(X_f[:,0], X_f[:,1], c=X_d[a])
    # plt.colorbar()

    # Rectangular domain
    X_f = valve.rect_coll(ncol=[9,5,5,5])
    X_fluid, X_d, _ = valve.rect_floaters_hard(X_f, inletfatness=10, carryalong=[], do_condition=True)

    plt.figure(figsize=(15*1.5,3*1.5))
    plt.scatter(X_f[0][:,0], X_f[0][:,1], label="fluid")
    plt.scatter(X_f[1][:,0], X_f[1][:,1], label = "inlet")
    plt.scatter(X_f[2][:,0], X_f[2][:,1], label = "outlet")
    plt.scatter(X_f[3][:,0], X_f[3][:,1], label = "wall")
    plt.legend()
    plt.colorbar()

    a = 2
    plt.figure(figsize=(15*1.5,3*1.5))
    plt.scatter(X_fluid[:,0], X_fluid[:,1], c=X_d[a])
    plt.colorbar()


# %%
